//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: System.Reflection.AssemblyVersion("3.8.5564.19735")]
[assembly: System.Reflection.AssemblyFileVersion("3.8.5564.19735")]
[assembly: System.Reflection.AssemblyInformationalVersion("3.8.20150327.19735")]


