using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using Twilio;

namespace Twilio.Monitor
{
    public class AlertResult : MetadataListBase
    {
        /// <summary>
        /// List of Alerts generated by the API.
        /// </summary>
        public List<Alert> Alerts { get; set; }
    }
}
