//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: System.Reflection.AssemblyVersion("1.1.5542.51604")]
[assembly: System.Reflection.AssemblyFileVersion("1.1.5542.51604")]
[assembly: System.Reflection.AssemblyInformationalVersion("1.1.20150305.51604")]


