//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: System.Reflection.AssemblyVersion("1.0.5556.46336")]
[assembly: System.Reflection.AssemblyFileVersion("1.0.5556.46336")]
[assembly: System.Reflection.AssemblyInformationalVersion("1.0.20150319.46336")]


